matrix:
  include:
    - language: node_js
      node_js:
        - "10"
    - language: python
      python:
        - "3.6.5"
      install:
        - pip install coverage
        - pip install requests
      script:
        - coverage run ./web_scraper/scraping_schedule.py
        - coverage report -m
        - codecov
