matrix:
  include:
    - language: node_js
      node_js:
        - "10"
    - language: python
      python:
        - "3.6.5"
      before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -qq python3.6.5
      install:
        - pip install coverage
      script:
        - coverage run tests.py

