matrix:
  include:
    - language: node_js
      node_js:
        - "10"
      install:
        - npm install -g codecov
      script:
        - npm test
      after_success:
        - codecov 
    - language: python
      python:
        - "3.6.5"
      install:
        - pip install coverage
        - pip install requests
      script:
        - coverage run ./web_scraper/tests.py
      after_success:
	- codecov
